---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Synapse-Monitor-Listener
no_index:
  directory:
    - t
    - inc
requires:
  Daemon::Generic: 0.82
  File::Copy: 2.1
  File::Touch: 0.08
  Synapse::CLI::Config: 0.1
  Time::HiRes: 1.9719
  YAML::XS: 0.38
version: 0.1
