--- #YAML:1.0
name:               Synapse-Monitor-Listener
version:            0.2
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Daemon::Generic:      0.82
    File::Touch:          0.08
    Synapse::CLI::Config:  0.1
    Synapse::Logger:      0.1
    Time::HiRes:          1.9719
    YAML::XS:             0.38
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
